apiVersion: v1
kind: Service
metadata:
  name: frontendservices
spec:
  selector:
    app: frontendservices
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendservices
  template:
    metadata:
      labels:
        app: frontendservices
    spec:
      containers:
        - name: frontendservices
          image: umang2001/blogapplication:frontendimage
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
