apiVersion: v1
kind: Service
metadata:
  name: commentservices
spec:
  selector:
    app: commentservices
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
  type: ClusterIP 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commentservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commentservices
  template:
    metadata:
      labels:
        app: commentservices
    spec:
      containers:
        - name: commentservices
          image: umang2001/blogapplication:commentimage
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
