apiVersion: v1
kind: Service
metadata:
  name: blogservices
spec:
  selector:
    app: blogservices
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogservices
  template:
    metadata:
      labels:
        app: blogservices
    spec:
      containers:
        - name: blogservices
          image: umang2001/blogapplication:blogimage
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
